Changed layout in UserAdminController
PHorvath1/ami_lara pull request #226
Opened 2021-12-14 07:58 UTC by tresze

Frontend is in sync with the admin panel in UserAdminController now.

2021-12-14 08:08 UTC, tresze commented
Also, the page does not throw an exception now. It is functioning properly.

2022-02-23 10:40 UTC, PHorvath1 commented on src/resources/views/pages/admin/Users/index.blade.php
> +                :as="['ID', 'Name', 'Email', 'Created At']"
This should not show the IDs of the users.

2022-02-23 10:42 UTC, PHorvath1 commented on src/resources/views/pages/admin/Users/index.blade.php
> +                :edit="true"
These lines will need some rework deeper because they redirect to `user/...` instead of `admin/user/...`.

2022-02-23 10:50 UTC, PHorvath1 commented on src/resources/views/pages/admin/Users/show.blade.php
> +@endsection
This page is a little bit off. Needs some design rework. Maybe try to put the information under each other.

2022-02-23 10:52 UTC, PHorvath1 requested changes
Overall nice job but it has some flaws that should be addressed.

2022-03-12 09:54 UTC, PHorvath1 approved these changes

2022-03-12 09:54 UTC, merged